alterando soma
monalisa36/calculadora-gqso pull request #5
Opened 2021-08-19 03:10 UTC by monalisa36

2021-08-24 11:42 UTC, annabeatrizsm commented on calc-api/src/main/java/app/Soma.java
>          }
É bom colocar um cometário de o que a função está fazendo no código. Exemplo: //Informar que o parâmetro inserido está incorreto

2021-08-24 11:45 UTC, annabeatrizsm commented on calc-api/src/main/java/app/Soma.java
>          catch (NumberFormatException nfe) {
É bom colocar um cometário de que a função está fazendo nenhum código. Exemplo: // Informar que o parâmetro inserido está incorreto

2021-08-24 11:48 UTC, annabeatrizsm requested changes
É bom fazer essa alteração para o melhor entendimento do código

2021-08-24 11:50 UTC, annabeatrizsm commented
Resolver, também, o problema dos arquivos conflitantes

2021-09-07 16:22 UTC, tayllane reviewed
É interessante colocar comentário no código para que o próprio desenvolver e outros possam identificar para que serve. Por exemplo: return String.format("%.1f", s); /* imprime o valor com ponto flutuante

2021-09-07 16:22 UTC, tayllane commented on calc-api/src/main/java/app/Soma.java
>              return String.format("%.1f", s);
É interessante colocar comentário no código para que o próprio desenvolver e outros possam identificar para que serve. Por exemplo: return String.format("%.1f", s); /* imprime o valor com ponto flutuante

2021-09-15 02:52 UTC, merged